[package]
name = "scad-viewer"
version.workspace = true
edition.workspace = true

[lib]
name = "scad_viewer"
path = "src/lib.rs"

[[bin]]
name = "scad-viewer"
path = "src/main.rs"

[dependencies]
egui = "0.33"
egui-winit = "0.33"
env_logger = "0.11"
glam = "0.30"
log = "0.4"
muda = "0.17"
pollster = "0.4"
rfd = "0.15"
scad-data = { path = "../scad-data" }
scad-scene = { path = "../scad-scene" }
scad-ui = { path = "../scad-ui" }
winit = "0.30"
