[package]
name = "scad-viewer"
version.workspace = true
edition.workspace = true

[lib]
name = "scad_viewer"
path = "src/lib.rs"

[dependencies]
app-server-core = { path = "../app-server-core" }
egui = "0.33"
scad-scene = { path = "../scad-scene" }
studio-common = { path = "../studio-common" }
scad-ui = { path = "../scad-ui" }
