[package]
name = "scad-ui"
version.workspace = true
edition.workspace = true

[dependencies]
scene = { path = "../scene" }
scad-data = { path = "../scad-data" }
gpui = { git = "https://github.com/zed-industries/zed.git", package = "gpui" }
glam.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
rfd = "0.15"
